before:
  hooks:
    - go mod tidy

builds:
  - id: gitname
    env:
      - CGO_ENABLED=0

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

brews:
  - name: gitname
    homepage: "https://github.com/alex-shpak/gitname"
    description: "Simple script to set git config properties in git repository based on remote url."
    github:
      owner: alex-shpak
      name: gitname
    commit_author:
      name: Alex Shpak
      email: alex-shpak@users.noreply.github.com

    folder: Formula
    url_template: "https://github.com/<repo_owner>/<repo_name>/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    dependencies:
      - git

    skip_upload: true

