# This file was generated by GoReleaser. DO NOT EDIT.
cask "gitname" do
  version "6"

  on_macos do
    on_arm do
      sha256 "0f8d6c024793d0f4774deafd4fc8e170bba2946a775360682aa3b49d6a8e9e0a"
      url "https://github.com/alex-shpak/gitname/releases/download/v#{version}/gitname_Darwin_arm#{version}4.tar.gz"
    end
    on_intel do
      sha256 "39cec50e8a20ee51136d2f511b064abb21f412b9c08f5683dc9f4c51c7bf8f6e"
      url "https://github.com/alex-shpak/gitname/releases/download/v#{version}/gitname_Darwin_x8#{version}_#{version}4.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f68264545a52bebeb14f3c7df90f6fc9fd19573e70053b94ad3a9c0a3895f24f"
      url "https://github.com/alex-shpak/gitname/releases/download/v#{version}/gitname_Linux_arm#{version}4.tar.gz"
    end
    on_intel do
      sha256 "70778dba7bc423de003ed0c40bd70cdac7fc1469d8de6d9e216230db141d67a2"
      url "https://github.com/alex-shpak/gitname/releases/download/v#{version}/gitname_Linux_x8#{version}_#{version}4.tar.gz"
    end
  end

  name "gitname"
  desc "Simple script to set git config properties in git repository based on remote url."
  homepage "https://github.com/alex-shpak/gitname"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "git",
    ]

  binary "gitname"

  # No zap stanza required
end
