# This file was generated by GoReleaser. DO NOT EDIT.
cask "gitname" do
  version "6"

  on_macos do
    on_arm do
      sha256 "d6214d1a2de2428adfad31705ae6407680e7151ee01c8b75d529c7637e8789dc"
      url "https://github.com/alex-shpak/gitname/releases/download/v#{version}/gitname_Darwin_arm#{version}4.tar.gz"
    end
    on_intel do
      sha256 "6e330e026d4a3aff47c24cbe9c21bdc493379c6bceed032460a53702fed233f5"
      url "https://github.com/alex-shpak/gitname/releases/download/v#{version}/gitname_Darwin_x8#{version}_#{version}4.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "e644a7542c1034cf142189d8845775bcdd9c3f0467fca3eb13786bbbe6a28133"
      url "https://github.com/alex-shpak/gitname/releases/download/v#{version}/gitname_Linux_arm#{version}4.tar.gz"
    end
    on_intel do
      sha256 "269b3e195af580ccbbada9af932e45e21392384761fcb7e1a21950c73c4e4d57"
      url "https://github.com/alex-shpak/gitname/releases/download/v#{version}/gitname_Linux_x8#{version}_#{version}4.tar.gz"
    end
  end

  name "gitname"
  desc "Simple script to set git config properties in git repository based on remote url."
  homepage "https://github.com/alex-shpak/gitname"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "git",
    ]

  binary "gitname"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gitname"]
    end
  end

  # No zap stanza required
end
