# This file was generated by GoReleaser. DO NOT EDIT.
class Gitname < Formula
    desc "Simple script to set git config properties in git repository based on remote url."
    homepage "https://github.com/alex-shpak/gitname"
    version "2"
    bottle :unneeded

    if OS.mac?
      url "https://github.com/alex-shpak/gitname/releases/download/v2/gitname_2_Darwin_x86_64.tar.gz"
      sha256 "c00ce998aa8d83e269661818724957393500d7981b6b139f5f121baa03597ee7"
    elsif OS.linux?
      if Hardware::CPU.intel?
        url "https://github.com/alex-shpak/gitname/releases/download/v2/gitname_2_Linux_x86_64.tar.gz"
        sha256 "6ef614cec45dd1ed4ec9596477a5f4e0afcb3f93b7bcf9b25609c3b5295c6f75"
      end
    end

    depends_on "git"

    def install
      bin.install "gitname"
    end
end
