# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitname < Formula
  desc "Simple script to set git config properties in git repository based on remote url."
  homepage "https://github.com/alex-shpak/gitname"
  version "5"

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/alex-shpak/gitname/releases/download/v5/gitname_5_Darwin_x86_64.tar.gz"
    sha256 "45c44f7e1845df29e271cbe12b852e33d89d6cbc4b9432b21a2d514b8fa5dbd0"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/alex-shpak/gitname/releases/download/v5/gitname_5_Darwin_arm64.tar.gz"
    sha256 "db5304834eddde259ab179cb64e71d426aa1d7e61ffe951d4fc12cbd706a23d4"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/alex-shpak/gitname/releases/download/v5/gitname_5_Linux_x86_64.tar.gz"
    sha256 "18ca6b3c8a506d13593ab4052be44385f8bb69ee3c185d99de9a6194a7a75e21"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/alex-shpak/gitname/releases/download/v5/gitname_5_Linux_arm64.tar.gz"
    sha256 "03759b45656880360d0b193e1ef387ee589c65002409a97c06e6a1313551f966"
  end

  depends_on "git"

  def install
    bin.install "gitname"
  end
end
